=== partizan1317/Tariffs/src/main/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        elementFormDefault="qualified">
        <element name="tariffs">
                <complexType>
                    <sequence>
                        <element name="phoneTariff"
                                 type="tns:PhoneTariff"
                                 minOccurs="2"
                                 maxOccurs="unbounded"/>
                        <element name="homeTariff"
                                 type="tns:HomeTariff"
                                 minOccurs="2"
                                 maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
        </element>
        <complexType name="Tariff">
            <sequence>
                <element name="name" type="string"/>
                <element name="payroll" type="double"/>
            </sequence>
            <attribute name="id" type="ID" use="required"/>
            <attribute name="operator" use="optional" default="A1">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="MTS"/>
                        <enumeration value="A1"/>
                        <enumeration value="Life"/>
                    </restriction>
                </simpleType>
            </attribute>
        </complexType>
        <complexType name="PhoneTariff">
            <complexContent>
                <extension base="tns:Tariff">
                    <sequence>
                        <element name="callMinutes" type="positiveInteger"/>
                        <element name="smsPrice" type="double"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        <complexType name="HomeTariff">
            <complexContent>
                <extension base="tns:Tariff">
                    <sequence>
                        <element name="routerType" type="string"/>
                        <element name="internetSpeed" type="double"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
</schema>

=== partizan1317/Tariffs/src/main/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <phoneTariff id="190" operator="MTS">
        <name>"Безлимитище</name>
        <payroll>18.90</payroll>
        <callMinutes>150</callMinutes>
        <smsPrice>0.2</smsPrice>
    </phoneTariff>
    <phoneTariff id="5605" operator="Life">
        <name>"Пенсионный"</name>
        <payroll>9.40</payroll>
        <callMinutes>100</callMinutes>
        <smsPrice>0.1</smsPrice>
    </phoneTariff>
    <homeTariff id="467" operator="A1">
        <name>"HomeSmart"</name>
        <payroll>25</payroll>
        <routerType>ADSL</routerType>
        <internetSpeed>50</internetSpeed>
    </homeTariff>
    <homeTariff id="1901" operator="A1">
        <name>"HomeLuxury"</name>
        <payroll>50</payroll>
        <routerType>"Ethernet (FTTB)"</routerType>
        <internetSpeed>150</internetSpeed>
    </homeTariff>
</tariffs>
