=== partizan1317/Tariffs/src/test/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs"
        elementFormDefault="qualified">
        <element name="tariffs">
                <complexType>
                    <sequence>
                        <element name="phone-tariff"
                                 type="tns:PhoneTariff"
                                 minOccurs="2"
                                 maxOccurs="unbounded"/>
                        <element name="home-tariff"
                                 type="tns:HomeTariff"
                                 minOccurs="2"
                                 maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
        </element>
        <complexType name="Tariff">
            <sequence>
                <element name="name" type="string"/>
                <element name="payroll" type="double"/>
            </sequence>
            <attribute name="id" type="positiveInteger" use="required"/>
            <attribute name="operator-type" use="optional" default="A1">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="MTS"/>
                        <enumeration value="A1"/>
                        <enumeration value="LIFE"/>
                    </restriction>
                </simpleType>
            </attribute>
        </complexType>
        <complexType name="PhoneTariff">
            <complexContent>
                <extension base="tns:Tariff">
                    <sequence>
                        <element name="call-minutes" type="positiveInteger"/>
                        <element name="sms-price" type="double"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
        <complexType name="HomeTariff">
            <complexContent>
                <extension base="tns:Tariff">
                    <sequence>
                        <element name="router-type" type="string"/>
                        <element name="internet-speed" type="double"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
</schema>

=== partizan1317/Tariffs/src/test/java/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <phone-tariff id="1" operator="MTS">
        <name>"Безлимитище</name>
        <payroll>18.90</payroll>
        <call-minutes>150</call-minutes>
        <sms-price>0.2</sms-price>
    </phone-tariff>
    <phone-tariff id="2" operator="Life">
        <name>"Пенсионный"</name>
        <payroll>9.40</payroll>
        <call-minutes>100</call-minutes>
        <sms-price>0.1</sms-price>
    </phone-tariff>
    <home-tariff id="3">
        <name>"HomeSmart"</name>
        <payroll>25</payroll>
        <router-type>ADSL</router-type>
        <internet-speed>50</internet-speed>
    </home-tariff>
    <home-tariff id="4">
        <name>"HomeLuxury"</name>
        <payroll>50</payroll>
        <router-type>"Ethernet (FTTB)"</router-type>
        <internet-speed>150</internet-speed>
    </home-tariff>
</tariffs>
